DROP table Worker;
CREATE TABLE Worker(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(100) NOT NULL,
                       age int,
                       education varchar(100),
                       position varchar(100)
);

INSERT INTO Worker (name, age, education, position) VALUES ('Pervyj',28,'Vyshee', 'TeamLead');
INSERT INTO Worker (name, age, education, position) VALUES ('Vtoroj',25,'Vyshee', 'Developer');
INSERT INTO Worker (name, age, education, position) VALUES ('Pomoshnik',23,'Nezak_Vyshee', 'Coder');
