DROP TABLE ValCursy;
CREATE TABLE ValCursy(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       ccy varchar(3) NOT NULL,
                       bccy varchar(3) NOT NULL,
                       buy varchar(12) NOT NULL,
                       sale varchar(12) NOT NULL
);

INSERT INTO ValCursy (ccy, bccy, buy, sale) VALUES ('USD','UAH', '41.10000', '41.66667');
INSERT INTO ValCursy (ccy, bccy, buy, sale) VALUES ('EUR','UAH', '44.44000', '45.24887');
