DROP table Trow;
CREATE TABLE Trow(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       data1 varchar(100) NOT NULL
);

INSERT INTO Trow (data1) VALUES ('Pervyj text');
INSERT INTO Trow (data1) VALUES ('Text Vtoroj vvod');
