DROP table Worker;
CREATE TABLE Worker(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(100) NOT NULL,
                       age int,
                       education varchar(100),
                       position varchar(100)
);

insert into Worker (name, age, education, position) values ('Pomoshnik', 23, 'Nezak_Vyshee', 'Coder');
insert into Worker (name, age, education, position) values ('Pervyj', 28, 'Vyshee', 'TeamLeader');
insert into Worker (name, age, education, position) values ('Trulikov', 37, 'Nezak_Vyshee', 'Coder');
insert into Worker (name, age, education, position) values ('Vtoroj', 25, 'Vyshee', 'Developer');
insert into Worker (name, age, education, position) values ('Mymra_Sestra_2', 37, 'Nezak vyshee', 'Coder-2');
insert into Worker (name, age, education, position) values ('Kuzya', 39, 'Vyshee', 'Coder-3');
insert into Worker (name, age, education, position) values ('Tyrlintec-Ryapotun', 45, 'Vyshee', 'Kuler');
insert into Worker (name, age, education, position) values ('Muraha', 43, 'Srednee', 'Coder-4');
